#!/bin/bash

foc="$(xprop -root _NET_ACTIVE_WINDOW | awk -F' ' '{print $NF}')"
if xprop -id "${foc}" | _NET_WM_STATE | grep -q _NET_WM_STATE_FULLSCREEN; then
    echo "Fullscreen window"
else
    i3lock -ef -c 505050
fi
