#!/bin/sh
#
sleep 2
xrandr --output VIRTUAL1 --off --output eDP1 --primary --mode 1600x900 --pos 2560x268 --rotate normal --output DP1 --off --output DP2-1 --off --output DP2-2 --mode 2560x1440 --pos 0x0 --rotate normal --output DP2-3 --off --output HDMI2 --off --output HDMI1 --off --output DP2 --off 
sleep 2
xrandr --output VIRTUAL1 --off --output eDP1 --mode 1600x900 --pos 4160x268 --rotate normal --output DP1 --off --output DP2-1 --off --output DP2-2 --primary --mode 2560x1440 --pos 1600x0 --rotate normal --output DP2-3 --mode 1600x1200 --pos 0x128 --rotate normal --output HDMI2 --off --output HDMI1 --off --output DP2 --off
