#!/bin/bash
xset dpms 0 0 0 &
[ -x /usr/bin/numlockx ] && /usr/bin/numlockx &
redshift-gtk &
xbindkeys &
firefox-beta &
telegram-desktop &
xfce4-terminal &
spotify &
slack &
nemo &
thunderbird &
whatsapp-web-desktop &
xautolock -time 10 -locker '~/.dotfiles/scripts/neatolock' -killer 'systemctl suspend' -notify 30 -detectsleep -killtime 30 &
exec i3
